seed: 42
n: null # Limit the amount of data that is read in

min_movie_rating_count: 100

paths:
  root: "${hydra:runtime.cwd}"
  data: "${paths.root}/data/movielens"
  

data:
  ratings_raw: "${paths.data}/ml-32m/ratings.csv"
  ratings_processed: "${paths.data}/processed/ratings.csv"

model:
  name: "simple"
  params: {}

training:
  test_size: 0.2

mlflow:
  experiment_name: "movielens_recommender_experiment"
