defaults:
  - exp/baseline_test

paths:
  root: "${hydra:runtime.cwd}"
  data: "${paths.root}/data/movielens"  

data:
  ratings_raw: "${paths.data}/ml-32m/ratings.csv"
  ratings_processed: "${paths.data}/processed/ratings.csv"

training:
  test_size: 0.2
