seed: 42
n: 1000

paths:
  root: "${hydra:runtime.cwd}"
  data: "${paths.root}/data/movielens"
  

data:
  ratings_raw: "${paths.data}/ml-32m/ratings.csv"

model:
  name: "simple"
  params: {}

training:
  test_size: 0.2

mlflow:
  experiment_name: "movielens_recommender_experiment"
